name: "Saakhi Blog Action"
description: "Updates the database if a new blog is added"
author: "Duxcore"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  # request-url:
  #   description: "The URL that the payload is sent to"
  #   required: true
  # authorization-secret:
  #   description: "The secret used to validate requests"
  #   required: true

runs:
  using: "node12"
  main: "dist/index.js"